### ISSUE TITLE
The version of Tensorflow

### ISSUE THREAD

**Issue by Brucewangxq** [ZhengyaoJiang/NLRL#2]
Which version of Tf is used in the experiments? For version 1.5, tf.batch_gather is not supported to use.

**Comment by Brucewangxq** [comment]
I almost give all the version of Tensorflow a try. Eventually,  1.11 is a comfortable version.

**Comment by fA1sEr** [comment]
> I almost give all the version of Tensorflow a try. Eventually, 1.11 is a comfortable version.

Thanks!!!

**Comment by ZhengyaoJiang** [comment]
@Brucewangxq  Thanks for the reminding! I'll update the readme file.
